# Generated by Django 5.1.2 on 2026-01-04 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['wpm', 'accuracy']},
        ),
        migrations.AddField(
            model_name='score',
            name='time',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Leaderboard',
        ),
    ]
